### ISSUE TITLE
CGI 인식할 수 없는 문자처리에러

### ISSUE THREAD

**Issue by moaoh** [42seoulWebserv/irc#103]
<img width="330" alt="image" src="https://github.com/42seoulWebserv/irc/assets/50203674/7a2ea6c9-0780-4048-b4f0-75b06bfdf3b4">

- 위에있는 그림과 같이 한글의 자음만 사용해서 `POST`나 `DELETE`에 해당 문자을 넣을 경우 error 처리가 따로 되지않는 오류가 있습니다.
<img width="162" alt="image" src="https://github.com/42seoulWebserv/irc/assets/50203674/7d91cae9-cdfd-43c9-ae0b-59f85a970964">

- 위에 그림과 같이 인식이 되지못하고 소켓이 열린 상태로 대기하다가 타임아웃이 발생된 이후에 소켓이 닫히게 되는 bug가 추가적으로 있어
처리가 추가적으로 필요할 거 같습니다.

<img width="300" alt="image" src="https://github.com/42seoulWebserv/irc/assets/50203674/9f5b3b1d-a55a-48d4-ba42-faa4e5a030e0">

- 추가적으로 control-c로 종료를 시켰을 경우 위와 같이 에러가 나오게됩니다.

**Comment by sindydwns** [comment]
확인 결과, 한글의 경우 유니코드이므로 cgi에 바디가 전달되는 과정에서 문자열의 길이를 해석하는 방식의 차이가 있어 생겨난 문제로 보입니다. c++로 개발된 부모프로세스는 한글 하나당 `3길이`로 해석하여 보내고 있지만 파이썬으로 개발된 자식프로세스에서는 한글 하나당 `1길이`로 보고 있기 때문에 파이썬에서는 차이인 `2길이`만큼을 추가로 받기 위해 대기 상태에 빠지게 되었습니다.

이 문제를 해결하기 위해 파이썬에서 유니코드 문자열의 길이가 아닌 아스키코드의 길이로 데이터를 읽어들이는 방법이 있는지 찾고 있지만 아직 찾지 못했습니다.

**Comment by moaoh** [comment]
<img width="500" alt="image" src="https://github.com/42seoulWebserv/irc/assets/50203674/32eaf07a-ee31-4ab8-84ce-6a4bc68e9244">

- 이야기해주신대로 `network tap`을 확인해서 확인해보니 따로 리퀘스트를 요구한 uri는 없는 거 같아요.

**Comment by sindydwns** [comment]
파이썬에서 데이터를 바이트 단위로 받는 방법을 찾았지만 그 값을 유니코드로 파일에 저장하는 방법은 어느정도 시간을 소요했음에도 찾지 못했습니다. 여기에 더 많은 시간을 투자하기에는 다른 이슈를 처리하는 것이 좋을 것 같아 적어도 오류가 나지 않는 이 상태로 pr을 올리겠습니다.
