### ISSUE TITLE
socket 에러 처리필요

### ISSUE THREAD

**Issue by moaoh** [42seoulWebserv/irc#105]
- `localhost:8080` 형식으로 저희가 구성한 기본 웹페이지의 접속한 후 가만히 대기를 하고 있으면 `timeout` 상황과 `close socket` 상황이 2번씩 발생 되는 오류가 있어 확인 후에 따로 처리가 필요할 거 같습니다.

<img width="227" alt="image" src="https://github.com/42seoulWebserv/irc/assets/50203674/b39b2ecf-0654-4c3d-b9b0-97801de9e33f">

- `redirection`을 사용한 이후에도 똑같이 오류가 발생이 됩니다.
<img width="224" alt="image" src="https://github.com/42seoulWebserv/irc/assets/50203674/e2772bb5-f194-4b4f-9e48-f27285806b0f">

**Comment by moaoh** [comment]
<img width="500" alt="image" src="https://github.com/42seoulWebserv/irc/assets/50203674/32eaf07a-ee31-4ab8-84ce-6a4bc68e9244">

- 이야기해주신대로 `network tap`을 확인해서 확인해보니 따로 리퀘스트를 요구한 uri는 없는 거 같아요.

**Comment by moaoh** [comment]
해당환경은 `dev` 브랜치에서 `curl localhost:8080`으로 접속 후 기다리면 위와같이 똑같은 상황이 연출이 됩니다.

**Comment by sindydwns** [comment]
m1환경의 서버에 접속 후 10분동안 둬 봤는데 같은 현상 재현이 안됩니다. 이 현상은 재현될때 다시 살펴보겠습니다.

**Comment by veggie-garden** [comment]
코드적의 문제보단 크롬 브라우저의 동작 방식의 차이가 문제인 것 같습니다. 고로 이 이슈는 닫습니다.
