### ISSUE TITLE
스트레스 테스트

### ISSUE THREAD

**Issue by sindydwns** [42seoulWebserv/irc#107]
siege를 사용한 스트레스 테스트를 다음과 같이 진행하면
```sh

siege 127.0.0.1:8080/static/sindy -v

```
위의 명령을 통해 webserv에 요청을 보내게 되면
<img width="581" alt="image" src="https://github.com/42seoulWebserv/irc/assets/25172705/2fe50cec-467e-4632-93ff-ebc4d316eadc">

처음에는 많은 요청을 모두 정상적으로 처리하다가 위 이미지의 같이 중간에 6.7초 소요되고 있습니다.
간헐적인 문제가 아닌, 주기적으로 항상 일어나고 있습니다.
원인을 찾아 수정해야 합니다.

**Comment by veggie-garden** [comment]
`home`의 `.siege`폴더 안에 `siege.conf` 안에서 `connection: keep-alive`로 변경하는 것으로 문제를 해결했습니다.
