### ISSUE TITLE
cgi check

### ISSUE THREAD

**Issue by sindydwns** [42seoulWebserv/irc#110]
- [x] Because you won’t call the CGI directly, use the full path as PATH_INFO.
- [x] Your program should call the CGI with the file requested as first argument.
- [x] The CGI should be run in the correct directory for relative path file access.

**Comment by moaoh** [comment]
1. 2. 에 경우에는 이미 지켜지고 있던 사항이었고, 
3. 에 경우에는 #113 `refactor: :bug: cgi path change ( +chdir )` 에서 해결이 되었습니다.
