### ISSUE TITLE
autoindex 오작동 오류 수정 필요

### ISSUE THREAD

**Issue by sindydwns** [42seoulWebserv/irc#114]
```nginx
http {
	root /Users/yonshin/Project/webserv/html;
	client_max_body_size 50m;
	autoindex off;
	index test.html;
	server {
		server_name localhost;
		client_max_body_size 50m;
		listen 8080;
		autoindex on;
		location / {
			accept_methods GET;
		}
	}
}
```
이 경우에 autoindex가 작동하지 않습니다. 확인이 필요합니다.

**Comment by moaoh** [comment]
https://github.com/42seoulWebserv/irc/blob/34186748b6bdee20879d9266fdacf9ab3889428a/src/config/LocationConfig.cpp#L8-L17

LocationConfig 해당 파트에서 `autoindex_(false)`가 항상 false로 고정이 되어있어서 생기는 오류였습니다.
`autoindex`를 `this->autoindex_ = src.getAutoindex()` 와 같은 형식으로 고치면 해결이 됩니다.
