### ISSUE TITLE
FileReadEventController && FileWriteEventController 테스트 요망

### ISSUE THREAD

**Issue by veggie-garden** [42seoulWebserv/irc#13]
- [x] 파일 권한 확인 (쓰기 권한이 없는 파일이 열리는지)
- [ ] 파일 읽기 또는 쓰는 도중에 block이 안되는지 확인
    - [ ] event.data가 local file을 읽었을 경우, 어떤 식으로 동작하는지 명확하게 알기
https://github.com/42seoulWebserv/irc/blob/25644db71208bf759aabdad09dc28c0a411231a2/src/FileReadEventController.cpp#L34-L38

**Comment by moaoh** [comment]
필요가 없어졌다고 합니다 🎉
