### ISSUE TITLE
PUT 메소드도 지원 필요

### ISSUE THREAD

**Issue by sindydwns** [42seoulWebserv/irc#24]
해당 코드에서 `GET`, `POST`, `DELETE` 메소드를 지원하고 `PUT`은 지원하지 않는 것으로 보입니다.
https://github.com/42seoulWebserv/irc/blob/d1c28e4acc5173676e9dcf8389723f1d49a5c846/src/ClientEventControllerRead.cpp#L72-L74

`PUT`도 지원하여 4개의 메소드를 구현하는 것을 어떨까요?

**Comment by sindydwns** [comment]
음.. 아니면 `PUT`은 과제에서 따로 요구하고 있지 않는 것 같은데 하지 말까요?

**Comment by veggie-garden** [comment]
토론 결과, `PUT`은 구현 안합니다.
