### ISSUE TITLE
(#46) segmentation fault - 원인

### ISSUE THREAD

**Issue by moaoh** [42seoulWebserv/irc#49]
서버에 `curl -X TEST localhost:8080` 과 같이 허용되지않은 method를 보낸경우에 segfault가 발생이되는 현상이 있습니다.
그 현상에 대한 원인이 허용되지않는 method가 들어온 경우에는 throw로 처리가 되어

https://github.com/42seoulWebserv/irc/blob/7d3a92a2ffacc564eac80d79af09aab6cc1945b3/src/processor/ParseRequestProcessor.cpp#L130-L136
로 들어오게 되는데
https://github.com/42seoulWebserv/irc/blob/7d3a92a2ffacc564eac80d79af09aab6cc1945b3/src/config/LocationConfig.cpp#L177-L182
해당 파트에서 `LocationConfig`이 비워져있는 반례 케이스가 있어 해결이 필요합니다.

**Comment by veggie-garden** [comment]
#46
