### ISSUE TITLE
FileReadEventController.cpp 리팩토링 - close 소멸자에서 호출

### ISSUE THREAD

**Issue by sindydwns** [42seoulWebserv/irc#59]
https://github.com/42seoulWebserv/irc/blob/1ac031f273146d5a89a283c8eabdc3d96cc78208/src/FileReadEventController.cpp#L39-L80
위 코드에서 return 전에 close 함수를 반복해서 보출하고 있습니다.
close 함수를 소멸자에서 따로 호출하는 코드가 더 보기 좋아보입니다.

**Comment by moaoh** [comment]
이미 없어진 파일입니다.
