### ISSUE TITLE
default error page

### ISSUE THREAD

**Issue by sindydwns** [42seoulWebserv/irc#8]
현재 구현 내용에서 과제의 요구사항을 충족하지 못한 부분이 있어 이슈로 남깁니다.
```
• You server must have default error pages if none are provided.
```
저희의 서버는 error page 를 설정할 수 있어야 하며 설정되지 않았다면 반드시 default error page 를 제공할 수 있어야 합니다.
에러 페이지에 대한 다양한 테스트를 진행했습니다.

nginx 기준으로 에러 페이지는 다음과 같이 설정합니다.
```
error_page 404 403 /error.html;
```
이 내용은, `root /var/www/html/;` 이 설정되어 있다면 404, 403이 발생했을때 `/var/www/html/error.html`파일을 제공하는 지시어입니다.
`/var/www/html/error.html`파일이 존재하지 않을 경우 nginx의 기본 404 메시지가 응답됩니다.
`/var/www/html/error.html`파일의 읽기 권한이 부족할 경우 403으로 응답하며 이때는 403에 해당하는 default error page가 제공됩니다. (403에 대한 에러페이지가 살정되었더라도 default error page 를 제공합니다.)

`error_page 404 403 /error.html;`와 `error_page 404 403 error.html;` 는 다르게 동작합니다. `/error.html` 이 아닌 `error.html`을 제공하고 있는데 이것이 어떤 경로의 파일을 의미하는지는 확인하지 못했습니다.

`error_page` 지시어는 `html` block, `server` block, `locaation` block 에서 사용할 수 있습니다.

**Comment by veggie-garden** [comment]
일단 지금 생각으로는 `/error.html`은 절대 경로를, `error.html`는 그 폴더 내의 상대 경로를 의미하는 것 같습니다. 지금 저희가 default error page도 제공하는 코드를 만들지 않아서 문제인 것인가요?

**Comment by sindydwns** [comment]
이 이슈는 11/8일 오프라인 회의에서 일단락되었습니다. 추가적인 내용은 https://github.com/42seoulWebserv/irc/discussions/10 여기에서 다룹니다.
